### ISSUE TITLE
Create an agnostic variant of the SE driver that automatically routes to the most suitable provider

### ISSUE THREAD

**Issue by paulhowardarm** [parallaxsecond/parsec-se-driver#7]
### Summary
This request is to create an SE driver layer that allows clients of PSA Crypto to use Parsec in a platform-agnostic fashion. The driver would choose the correct provider based on information obtained from the service. Client code would then not have any compile-time coupling with a particular Parsec provider type (such as TPM). A common client build would be usable with multiple Parsec back-end providers.

### Background
To consume the Parsec service into C code, we are using the PSA Crypto API as the programming surface, and Mbed Crypto as the glue layer to the Parsec client library. Mbed Crypto uses **secure element (SE) drivers** as a way of routing crypto operations to the correct place. Clients register these drivers and then use key `lifetime` properties as a way of specifying the SE driver that should be used.

This repo holds SE drivers that can be used to route PSA Crypto operations to Parsec.

However, Parsec itself is an abstraction that can have multiple implementations depending on the platform. These implementations are known as **providers**. Parsec has different providers for different types of platform hardware such as TPM or HSM.

The model we've adopted for the SE driver so far is that there is a precise 1-1 mapping between an SE driver and a Parsec provider. So, if you want to use a TPM platform, then you would use the TPM SE driver, which in turn would select for the TPM Parsec provider.

This model is conceptually quite clean, but it does mean that the client code needs full awareness of the platform in order to register the correct SE driver and use the correct key lifetimes for it. This is a tight coupling that might not always be desirable. Parsec is intended to be a platform-agnostic API, so client application code shouldn't be required to have this level of awareness unless it wants to.

It should be possible for an SE driver to select the Parsec provider automatically based on its configured knowledge of the platform. Client code can then just use a generic "Parsec" key lifetime and everything else is automatic.

With this variant of the SE driver, adopters of Parsec can have common application code on any platform.

### Details

- Existing SE drivers can remain as they are. There might be some cases where an explicit client-side selection is desirable.
- We would introduce a new SE driver structure and associated key lifetime (names TBD).
- The new SE driver would choose its Parsec provider by listing the available providers in the service. In many cases, there is only one kind of platform hardware available, so the list of crypto providers may be a list of only one entry anyway. However, this cannot be guaranteed, so we would need to consult a preferentially-ordered list. This could be done by calling the existing **ListProviders** opcode, and treating the list as a preferential order (with the core provider filtered out). Or we could introduce a whole new opcode to produce the list, which avoids retro-fitting any kind of ordering semantics to the existing opcode, but requires more effort.

### Client Code
Client C code would be completely agnostic and have no compile-time tie to any particular platform. The same builds could be used on TPM and non-TPM platforms, for example. The way of using Parsec would simply be to specify Parsec as the key lifetime, and everything else would be automatic.

**Comment by hug-dev** [comment]
I totally agree with the general idea, that will make a better experience for clients. A few comments:

> Existing SE drivers can remain as they are. There might be some cases where an explicit client-side selection is desirable.

I think we could either keep the current one and create a new SE driver structure:
* `PARSEC_TPM_DIRECT_SE_DRIVER` that currently exists
* `PARSEC_DIRECT_SE_DRIVER` to create
So that there would be some duplication of code (but only the `p_init` method is actually to change).
Or we could keep a single `PARSEC_DIRECT_SE_DRIVER` structure and have compile-time features to choose if we explicitely want to hardcode a specific provider. That way, there is no duplication of code (and probably scale better if we don't want to have 3 structures: one generic, one for TPM, one for PKCS11).

> This could be done by calling the existing ListProviders opcode, and treating the list as a preferential order (with the core provider filtered out). Or we could introduce a whole new opcode to produce the list, which avoids retro-fitting any kind of ordering semantics to the existing opcode, but requires more effort.

I am more in favor of using the existing operation and adding the new semantic of preferential order. Mostly because I think the semantic added makes sense, is small, and almost effort-less to add. I actually think that we are currently maintaining the order of providers in the `config.toml` file in the result of `ListProviders` so adding this feature would mostly be changes in the book, adding tests, and in the `p_init` method of the SE driver.

**Comment by ionut-arm** [comment]
> Or we could keep a single PARSEC_DIRECT_SE_DRIVER structure and have compile-time features to choose if we explicitely want to hardcode a specific provider. That way, there is no duplication of code (and probably scale better if we don't want to have 3 structures: one generic, one for TPM, one for PKCS11).

Features in Rust are so well supported and make the code so nice to read in cases like this; I'd definitely like the idea of having one "big" SE driver that implements all of them with the option of enabling a feature to get a restricted driver.

**Comment by hug-dev** [comment]
parallaxsecond/parsec#197 has been merged to make sure that on the Parsec side, the order of ListProviders is kept the same. A PR will be open on this repo as well, and in the book.
